### PR TITLE
optimize repository

### PR DESCRIPTION
**Pull request by Sibiraj-S**
* Just optimization stuffs

### CODE REVIEW

**Comment by Sibiraj-S** [comment]
@optimistex . What do you think. I felt the repository was little clumsy. Made some changes. 😕

**Comment by Sibiraj-S** [comment]
@optimistex . This is as same as the previous one. Just a little straight forward.

**Comment by optimistex** [comment]
> What do you think. I felt the repository was little clumsy. Made some changes.

Hi. Grateful for contributing!
It's accepted.

> If this is fine I have few more tweaks for the development environment too.

What the tweaks?

**Comment by Sibiraj-S** [comment]
1. Using standard version for changelog generation and sematic versioning
2. Use commitizen and conventional changelog for commit messages
4. Prefer husky instead of `pre-commit`
5. @types/webpack is an unused/extra devDependency 
3. Automated releasing to GitHub
4. Automated publishing from Travis

More stuff may add up while working 😺

**Comment by Sibiraj-S** [comment]
@optimistex. Which editor are you using?

**Comment by optimistex** [comment]
> Which editor are you using?

PhpStorm
image

**Comment by Sibiraj-S** [comment]
I would recommend vscode for angular2+ projects.

**Comment by optimistex** [comment]
Thanks. But...
My general project contains backend on PHP and frontend on Angular. It is two different repositories. And I'm working on it together with PhpStrom. It is very useful for me.

And a year ago I tried vscode, but it has less functions by comparing with PhpStorm. It is critical for me.

**Comment by Sibiraj-S** [comment]
Cool then,

Also give that editor a try when you are free. Lots of things are changed.

**Comment by optimistex** [comment]
Ok, I will keep in mind.

**Pull request merged**
