### PR TITLE
conventional commits and semantic releasing

### PR DESCRIPTION
**Pull request by Sibiraj-S**
* removed `pre-commit` installed `husky`
* installed `commitizen`, `cz-conventional-changelog` and `standard-version`

### CODE REVIEW

**Comment by Sibiraj-S** [comment]
I think with this setup you will be able to publish from travis. 

1. use `npm run cz` for commit, more info here https://github.com/commitizen/cz-cli
2. For releasing run `npm run release`, more info here https://github.com/conventional-changelog/standard-version
3. set your email and token in travis environmental variable, for setting token encryption check here for more information https://docs.travis-ci.com/user/deployment/npm/
4. push using git push --follow-tags origin master. 

You are done. Hope this helps. 😸

**Comment by Sibiraj-S** [comment]
The last step I was unable to test. Make sure it is working @optimistex

**Comment by optimistex** [comment]
> use `npm run cz` for commit, more info here https://github.com/commitizen/cz-cli

I tried to use the `npm run cz`. But it is not useful for me. I have use tools fo PhpStrom.
image

But okay. Let it be in the scripts. Maybe it will be useful for somebody!?
_________
> For releasing run npm run release, more info here https://github.com/conventional-changelog/standard-version

I will try it to use. I did little tune it.
_________
> set your email and token in Travis environmental variable, for token encryption check here for more information https://docs.travis-ci.com/user/deployment/npm/

I want to have a full control over it. That I have commented the deploy in the travis config
_________
> push using git push --follow-tags origin master.

Thanks for instructions but I do it with PhpStorm:
image

**Comment by Sibiraj-S** [comment]
Its your call 😄 . Also, thanks for maintaining the repo. I have been using in my project

**Comment by optimistex** [comment]
You are welcome!
And thanks for contributing!

**Pull request merged**
